version: '2'

services:
  pihole:
    container_name: pihole
    hostname: pi-hole
    build: .
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '80:80/tcp'
      - '443:443/tcp'
    environment:
      TZ: 'America/New_York'
      PIHOLE_DNS_: '127.0.0.1#5335'
      DNSSEC: 'true'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - './etc-pihole-updatelists/:/etc/pihole-updatelists/'
    restart: unless-stopped
